#server.port=80
#app.environment=prod

#logging.level.root=WARN

# Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LeaveManager
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    database: postgresql

