version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/leave-manager
    docker:
      - image: circleci/openjdk:11.0.2-jdk

    steps:
      # git pull
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: circleci-leave-manager-{{ checksum "pom.xml" }}

      #  Gets the project dependencies
      - run: mvn dependency:go-offline

      #  Saves the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-leave-manager-{{ checksum "pom.xml" }}

      # Run tests
      - run: mvn package

      # Run codecov
      - codecov/upload:
          file:

      # Uploads the test metadata
      - store_test_results:
          path: target/surefire-reports

      # Store the jar as an artifact
      - store_artifacts:
          path: target/leave-manager-*.jar

      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples